# Generated by Django 2.2.4 on 2021-03-04 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pap', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='project',
            new_name='task',
        ),
    ]
